// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY
// If you want to change the content of this file, you need to edit
// file '/dictionaries/ru.po' and run '.po' extractor
export const base = {
  'components.organisms.Header.app': 'Кабинет',
  'components.organisms.Header.signIn': 'Вход',
  'components.organisms.Header.signOut': 'Выход',

  'components.organisms.SocialButtons.facebook': 'Facebook',
  'components.organisms.SocialButtons.google': 'Google',

  'components.organisms.forms.ConfirmEmailForm.continue': 'Продолжить',
  'components.organisms.forms.ConfirmEmailForm.placeholderCode': 'Код',
  'components.organisms.forms.ForgotPasswordChangeForm.continue': 'Продолжить',
  'components.organisms.forms.ForgotPasswordChangeForm.placeholderPassword':
    'Пароль',
  'components.organisms.forms.ForgotPasswordForm.placeholderEmail': 'Email',
  'components.organisms.forms.ForgotPasswordForm.send': 'Отправить',
  'components.organisms.forms.SignInEmailForm.placeholderEmail': 'Email',
  'components.organisms.forms.SignInEmailForm.placeholderPassword': 'Пароль',
  'components.organisms.forms.SignInEmailForm.signIn': 'Войти',
  'components.organisms.forms.SignUpEmailForm.placeholderEmail': 'Email',
  'components.organisms.forms.SignUpEmailForm.placeholderPassword': 'Пароль',
  'components.organisms.forms.SignUpEmailForm.placeholderRole': 'Роль',
  'components.organisms.forms.SignUpEmailForm.signUp': 'Зарегистироваться',

  'components.routes.modals.ConfirmEmail.sendAgain': 'Отправить код повторно',
  'components.routes.modals.ConfirmEmail.text': 'Введите код',
  'components.routes.modals.ConfirmEmail.title':
    'Подтверждение адреса электронной почты',
  'components.routes.modals.ForgotPassword.remember': 'Войти',
  'components.routes.modals.ForgotPassword.text':
    'Если вы забыли пароль, укажите ваш email в форме ниже, и мы пришлем вам инструкции по восстановлению доступа',
  'components.routes.modals.ForgotPassword.title': 'Забыл пароль',
  'components.routes.modals.ForgotPasswordChange.continue': 'Продолжить',
  'components.routes.modals.ForgotPasswordChange.text': 'Введите новый пароль',
  'components.routes.modals.ForgotPasswordChange.title': 'Изменение пароля',
  'components.routes.modals.Profile.TabTitleInfo': 'Информация',
  'components.routes.modals.Profile.TabTitleSettings': 'Настройки',
  'components.routes.modals.Profile.title': 'Мой профиль',
  'components.routes.modals.ProfileId.title': 'Профиль',
  'components.routes.modals.SignInEmail.forgotPassword': 'Забыли пароль?',
  'components.routes.modals.SignInEmail.register': 'Регистрация',
  'components.routes.modals.SignInEmail.signIn': 'Войти через',
  'components.routes.modals.SignInEmail.title': 'Вход',
  'components.routes.modals.SignUpEmail.isExist': 'Уже есть аккаунт?',
  'components.routes.modals.SignUpEmail.register': 'Зарегистироваться через',
  'components.routes.modals.SignUpEmail.title': 'Регистрация',

  'components.routes.pages.App.title': 'Template',
  'components.routes.pages.Error404.text': 'Страница не найдена',
  'components.routes.pages.Error404.title': '404',
  'components.routes.pages.Root.title': 'Template',
};
