// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY
// If you want to change the content of this file, you need to edit
// file '/dictionaries/ru.po' and run '.po' extractor
export const events = {
  'error.confirmationCode.expired': 'Код подтверждения устарел',
  'error.confirmationCode.notValid': 'Неверный код подтверждения',

  'error.email.alreadyExists': 'Пользователь с таким email уже существует',
  'error.email.minLength': 'Email слишком короткий',
  'error.email.notValid': 'Неверный email',
  'error.email.wrongFormat': 'Неверный формат электронной почты',

  'error.emailOrPassword.notValid': 'Неверный email или пароль',

  'error.endpoint.invalidId': 'Неверный id',
  'error.endpoint.notValid': 'Эндпоинт настроен некорректно',

  'error.field.required': 'Это поле является обязательным',

  'error.login.alreadyLoggedIn': 'Вы уже авторизованы',
  'error.login.need': 'Сначала необходимо авторизоваться',

  'error.media.insufficientStorage': 'недостаточно места для хранения',
  'error.media.invalidFormData': 'Не верные данные формы',
  'error.media.invalidType': 'Не верный тип файла',
  'error.media.sizeTooLarge': 'Размер файла слишком большой',

  'error.password.minLength': 'Пароль слишком короткий',
  'error.password.notValid': 'Неверный пароль',

  'error.permissionDenied': 'Доступ запрещен',

  'error.terms.needToAccept': 'Вам необходимо принять условия обслуживания',

  'error.user.invalidDate': 'Неверная дата',
  'error.user.lackOfFunds': 'Недостаточно средств',
  'error.user.notFound': 'Пользователь не найден',
};
