// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY
// If you want to change the content of this file, you need to edit
// file '/dictionaries/ru.po' and run '.po' extractor
export const base = {
  'services.notifications.email.attachments': 'Вложения: ${text}',
  'services.notifications.email.changeEmail.text1':
    'Была предпринята попытка изменить адрес электронной почты в вашей учетной записи!',
  'services.notifications.email.changeEmail.text2.0':
    'Чтобы завершить процесс изменения адреса электронной почты, перейдите по ссылке: {link}',
  'services.notifications.email.changeEmail.text2.1':
    'Чтобы завершить процесс изменения адреса электронной почты, {link}.',
  'services.notifications.email.changeEmail.text2.2': 'нажмите сюда',
  'services.notifications.email.changeEmail.title':
    'Пожалуйста, подтвердите новый адрес электронной почты',
  'services.notifications.email.changePassword.text1':
    'Вы получили это письмо, так как изменили пароль для входа в Template.',
  'services.notifications.email.changePassword.text2':
    'Если это были не вы, свяжитесь со службой поддержки: {email}.',
  'services.notifications.email.changePassword.text3':
    'Если это были вы, ничего делать не нужно.',
  'services.notifications.email.changePassword.title': 'Ваш пароль был изменён',
  'services.notifications.email.changed.text':
    'На вашем аккаунте был изменен адрес email. С {oldEmail} на {newEmail}',
  'services.notifications.email.changed.title': 'Ваша почта была изменена',
  'services.notifications.email.forgotPassword.text1':
    'Вы получили это письмо, так как запросили восстановление пароля для входа в Template',
  'services.notifications.email.forgotPassword.text2.0':
    'Перейдите по ссылке, чтобы задать себе новый пароль: {link}',
  'services.notifications.email.forgotPassword.text2.1':
    '{link}, чтобы задать себе новый пароль.',
  'services.notifications.email.forgotPassword.text2.2': 'Нажмите сюда',
  'services.notifications.email.forgotPassword.text3':
    'Если это были не вы, просто проигнорируйте данное письмо.',
  'services.notifications.email.forgotPassword.title': 'Восстановление пароля',
  'services.notifications.email.forgotPasswordChange.text1':
    'Вы получили это письмо, так как прошли процедуру восстановления и смены пароля для входа в Template',
  'services.notifications.email.forgotPasswordChange.text2':
    'Если это были не вы, свяжитесь со службой поддержки: {email}',
  'services.notifications.email.forgotPasswordChange.text3':
    'Если это были вы, ничего делать не нужно.',
  'services.notifications.email.forgotPasswordChange.title':
    'Ваш пароль был изменен',
  'services.notifications.email.regards': 'С уважением,{br}Template',
  'services.notifications.email.signUpEmail.text1':
    'Благодарим вас за регистрацию!',
  'services.notifications.email.signUpEmail.text2.0':
    'Чтобы завершить процесс регистрации, перейдите по ссылке: {link}',
  'services.notifications.email.signUpEmail.text2.1':
    'Чтобы завершить процесс регистрации, {link}.',
  'services.notifications.email.signUpEmail.text2.2': 'нажмите сюда',
  'services.notifications.email.signUpEmail.title':
    'Пожалуйста, подтвердите свой адрес электронной почты',
};
